### PR TITLE
Dice game added

### PR DESCRIPTION
**Pull request by Shreyan-12345**
Added a dice game

### CODE REVIEW

**Comment by Shreyan-12345** [comment]
pls merge this

**Comment by Shreyan-12345** [comment]
> @microsoft-github-policy-service agree [company=" "]


 I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

**Comment by 11nitis** [comment]
Hey! Shreyan can you assign this to me

**Comment by 11nitis** [comment]
can you assign this task to me ?

**Comment by 11nitis** [comment]
@Microsoft hey! can you assign this project  to me.

**Comment by Shreyan-12345** [comment]
> 
@microsoft-github-policy-service agree

**Comment by Shreyan-12345** [comment]
> Added a dice game

@microsoft pls assign me this

**Comment by Googler1** [comment]
Not mine ours.

**Comment by saragibby** [comment]
Thank you @Shreyan-12345 for your suggestion. This is a fun project. For now, as this is a great project for additional practice, the best place to share your creation would be in [**Show and Tell**](https://github.com/microsoft/Web-Dev-For-Beginners/discussions/categories/show-and-tell).

Closing this PR so you can share this sample project within Discussions. When we build out the ability to onboard additional projects to our repo for extra practice and exercises, we will announce to the community. Thank you!

**Pull request closed without merging**
