### PR TITLE
Translation hi

### PR DESCRIPTION
**Pull request by San1ay**
😊

**Status**

- [x] 1.1
- [x] 1.2
- [x] 1.3
- [x] 1

- [x] 2.1
- [x] 2.2
- [x] 2.3
- [x] 2.4

- [x] 3.1
- [x] 3.2
- [x] 3.3

- [x] 4.typing-game

- [x] 5.1
- [x] 5.2
- [x] 5.3

- [x] 7.1
- [x] 7.2
- [x] 7.3
- [x] 7.4

- [x] README
- [x] for-teachers

### CODE REVIEW

**Comment by Moelee304octo** [comment]
~~**_[@```

```]()_**~~

**Comment by jlooper** [comment]
Wow! Thank you for this! I’ll find a reviewer 🙏

**Comment by San1ay** [comment]
> Wow! Thank you for this! I’ll find a reviewer 🙏

Okay mam🙂

**Comment by jlooper** [comment]
Thank you! 🙏♥️

**Pull request merged**
