### PR TITLE
translation to hi(Hindi)

### PR DESCRIPTION
**Pull request by San1ay**
😊

**Status**

- [x] 1.1
- [x] 1.2
- [x] 1.3

- [x] 2.1
- [x] 2.2
- [x] 2.3
- [x] 2.4
- [x] 2

- [x] 3.1
- [x] 3.2
- [x] 3.3
- [x] 3

- [x] 4

- [x] 5.1
- [x] 5.2
- [x] 5.3
- [x] 5 

- [x] 6.1
- [x] 6.2
- [x] 6.3
- [x] 6.4
- [x] 6.5
- [x] 6.6

- [x] 7.1
- [x] 7.2
- [x] 7.3
- [x] 7.4
- [x] 7-api
- [x] 7-solution
- [x] 7-bank-project

- [x] lesson-template

- [x] quiz-app

### CODE REVIEW

**Comment by San1ay** [comment]
Why my commits are failing build ?

**Comment by jlooper** [comment]
> Why my commits are failing build ? 

Don’t worry about it, it’s the quiz app refusing to build external PRs

**Review by jlooper — APPROVED** [review]
just amazing. Thank you so much!

**Comment by San1ay** [comment]
> hi @San1ay - thank you so much for these translations. Will you also translate the lessons themselves to Hindi (they are the README files in the translations folders)

Yup,Sure but currently I've to prepare for my upcoming exam. I'll do it soon as i get time🙂.

**Comment by jlooper** [comment]
> > hi @San1ay - thank you so much for these translations. Will you also translate the lessons themselves to Hindi (they are the README files in the translations folders)
> 
> Yup,Sure but currently I've to prepare for my upcoming exam. I'll do it soon as i get time🙂.

Thank you again and best of luck with your exams!

**Pull request merged**
