### PR TITLE
Faster Performance

### PR DESCRIPTION
**Pull request by caykey**

### CODE REVIEW

**Review by tascord — COMMENTED** [review]
Seems rather irrelivant.

**Review by jlooper — COMMENTED** [review]
This is a big change that will entail a lesson rewrite

**Review by synr760 — APPROVED** [review]

**Comment by 0Milkesa** [comment]
I don know how it work please help

**Comment by jlooper** [comment]
Closing this as it will entail a large rewrite

**Comment by 0Milkesa** [comment]
So what shall i do for learn

**Comment by jlooper** [comment]
> So what shall i do for learn
> […](#)

Please start with the root README

**Pull request closed without merging**
