### PR TITLE
Added hindi version to the readme.md file.

### PR DESCRIPTION
**Pull request by mrbuddhu**
Added Hindi version of the readme.md file to make it more accessible to Hindi audience.

### CODE REVIEW

**Comment by mrbuddhu** [comment]
@mattetti @chanezon @arschles @fhinkel Please look into it !

**Comment by sinedied** [comment]
Hi @mrbuddhu, it seems there's already a Hindi version located under `translations/readme.hi.md`.

Maybe you could look at it and see if it can be improved?
Please have a look at this document if you would like to help with translations: https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/TRANSLATIONS.md

**Comment by saragibby** [comment]
@mrbuddhu with the Hindi translation already existing at `translations/readme.hi.md` (https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/translations/README.hi.md), which has since been updated since this PR was updated. I'm going to close this one so that you can review the existing Hindi readme and open a new PR with any updates you find. Thank you!

**Comment by mrbuddhu** [comment]
Ok. Thanks

**Pull request closed without merging**
