### PR TITLE
Library Management (Basic JS and LocalStorage)

### PR DESCRIPTION
**Pull request by samipak458**
I would like to add my project.

A library management project that is easy to use and easy to understand. I used all the basic concepts of JS and LocalStorage in this project and I want to share my project to help other learner to understand the basic concepts of JS. I made this project using HTML, CSS, Bootstrap and JS. I also hosted this website using Azure Static Web Apps service.

Website: [Online Library](https://delightful-coast-00b51a700.1.azurestaticapps.net/)

### CODE REVIEW

**Comment by samipak458** [comment]
@jlooper kindly review it.

**Comment by jlooper** [comment]
hi @samipak458 - thank you for suggesting this contribution. We aren't accepting new lessons to the repo, but rather are prioritizing any translation work. However, I'd recommend reshaping this into a workshop for aka.ms/workshopomatic as it might work well for a web/mobile workshop concept. Thank you again!

**Comment by softchris** [comment]
@samipak458 thank you so much for writing this. As Jen said, we love contributions. Let me know if you have any questions, I'm on @chris_noring at Twitter as well.

**Comment by samipak458** [comment]
Sure, I will ask if I have any questions. Thank you

**Pull request closed without merging**
