### PR TITLE
Add portuguese br translation quizz

### PR DESCRIPTION
**Pull request by jessicaribeiroalves**
Adding the Portuguese-BR translation file to the quizz following the [specified guidelines](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/TRANSLATIONS.md).

### CODE REVIEW

**Comment by jessicaribeiroalves** [comment]
> @jessicaribeiroalves please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="{your company}"]

**Comment by jessicaribeiroalves** [comment]
@microsoft-github-policy-service agree

**Review by PabloNunes — COMMENTED** [review]
Review:

- Translation to Brazilian Portuguese
- Fixed some small errors

Status: Approved

**Comment by jessicaribeiroalves** [comment]
@PabloNunes and @leestott thanks for reviewing my PR!
I took a look at the pipeline failure. At the build and deploy job it's saying the deployment_token was not provided. Is there any action on my side that I can take?

**Comment by PabloNunes** [comment]
> @PabloNunes and @leestott thanks for reviewing my PR! I took a look at the pipeline failure. At the build and deploy job it's saying the deployment_token was not provided. Is there any action on my side that I can take?

Don't worry, your doc just changed documentation. Going ahead with merge.

**Pull request merged**
