### PR TITLE
I have added important HTML,CSS code for beginners to building websites

### PR DESCRIPTION
**Pull request by im-kamil**

### CODE REVIEW

**Review by im-kamil — COMMENTED** [review]
created by myself

**Comment by im-kamil** [comment]
> @im-kamil please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

sure

**Review by syedhassanulhaque — APPROVED** [review]
Well code by him

**Review by Sticknmove — APPROVED** [review]

**Review by Sticknmove — APPROVED** [review]
Thanks

**Review by Sticknmove — APPROVED** [review]
Thanks

**Review by Sticknmove — COMMENTED** [review]
Thanks

**Review by Sticknmove — APPROVED** [review]
Thanks

**Review by Sticknmove — APPROVED** [review]
Thanks

**Review by Sticknmove — APPROVED** [review]
Thanks

**Review by Sticknmove — APPROVED** [review]
Thanks

**Review by Sticknmove — APPROVED** [review]

**Comment by saragibby** [comment]
Thank you for your suggestion to add this project! We are currently not expanding this to any new lessons and projects. But stay tuned for when we open contributions for additional lessons, and example web apps to build. For now, sharing your creations within [Discussions](https://github.com/microsoft/Web-Dev-For-Beginners/discussions) would be amazing!

**Pull request closed without merging**
