### PR TITLE
 Fix link translation (FR) for README 

### PR DESCRIPTION
**Pull request by cballevre**
* Fix link translation for README.fr.md.

### CODE REVIEW

**Review by saragibby — APPROVED** [review]
Thank you for finding and correcting these translations!

**Comment by saragibby** [comment]
@cballevre looks like there is a conflict to resolve. Once you can resolve that, we'll get this merged in. Thank you!

**Comment by saragibby** [comment]
@cballevre looks like there is a conflict to resolve. Once you can resolve that, I will

**Comment by cballevre** [comment]
@saragibby Sry but I can't merge because I'm a first-time contributors so I need a maintainer to approve running workflows. Is it possible to approve it?

**Comment by saragibby** [comment]
Thanks for resolving the merge conflicts @cballevre! Appreciate your time to update these translations 🙌

**Pull request merged**
