### PR TITLE
[WIP] Add korean translations

### PR DESCRIPTION
**Pull request by minwook-shin**
WIP
I interested in this project, so I started translating Korean.

- [x] 1
- [x] 1-1
- [x] 1-2
- [x] 1-3 

- [x] 2
- [x] 2-1
- [x] 2-2
- [x] 2-3
- [x] 2-4

- [x] 3
- [x] 3-1
- [x] 3-2
- [x] 3-3

- [x] 4

- [x] 5
- [x] 5-1
- [x] 5-2
- [x] 5-3

- [x] 6
- [x] 6-1
- [x] 6-2
- [x] 6-3
- [x] 6-4
- [x] 6-5
- [x] 6-6

- [x] 7
- [x] 7-1
- [x] 7-2
- [x] 7-3
- [x] 7-4

### CODE REVIEW

**Comment by jlooper** [comment]
very cool! thank you!

**Comment by minwook-shin** [comment]
note : merged https://github.com/microsoft/Web-Dev-For-Beginners/pull/38

**Comment by Hiearl77** [comment]
Good 😊

**Comment by minwook-shin** [comment]
hello, @jlooper. 
All done. converted to pull request. please merging this.

**Comment by jlooper** [comment]
this is just amazing, Minwook-shin, thank you so much!

**Review by jlooper — APPROVED** [review]

**Comment by jlooper** [comment]
beautiful!

**Pull request closed without merging**
