### PR TITLE
Translating to Malay language (In Progress)

### PR DESCRIPTION
**Pull request by EugeneGohh**
Hi there, I have started working on translating 24 lessons to the Malay language ('Bahasa Melayu')  .
 # Status
- [x] 1
- [x] 1-1
- [x] 1-2
- [x] 1-3
- [x] 2
- [x] 2-1
- [x] 2-2
- [x] 2-3
- [x] 2-4
- [x] 3
- [x] 3-1
- [x] 3-2
- [x] 3-3
- [x] 4
- [x] 4-1
- [x] 5
- [x] 5-1
- [x] 5-2
- [x] 5-3 (assignment)
- [x] 5-3 (README)
- [x] 5-start
- [x] 5-solution
- [x] 6
- [x] 6-1
- [x] 6-2
- [x] 6-3 README.ms.md
- [x] 6-3 assignment
- [x] 6-4
- [x] 6-5
- [x] 6-6
- [x] 7
- [x] 7-1
- [x] 7-2
- [x] 7-3
- [x] 7-4
- [x] 7-api
- [x] 7-solutions

### CODE REVIEW

**Comment by jlooper** [comment]
hi, can I get a status update on these translations? thanks!

**Comment by EugeneGohh** [comment]
> hi, can I get a status update on these translations? thanks!

Sorry, I have been busy for the past few weeks. I will complete this before February.

**Comment by EugeneGohh** [comment]
Completed.

**Review by jlooper — APPROVED** [review]
Marvelous, and thank you for catching the English typos!

**Pull request merged**
