### PR TITLE
[WIP] translate 1-getting-started-lessons into Chinese

### PR DESCRIPTION
**Pull request by morenyang**
I am going to translate Ch1 into Chinese. 
That's quite an interesting job. 

- [x] README
- [x] 1-1
- [ ] 1-2
- [ ] 1-2

### CODE REVIEW

**Comment by jlooper** [comment]
So excited! thank you, xie xie!!

**Comment by SmashedFrenzy16** [comment]
ok

**Comment by jlooper** [comment]
A note, please make sure to translate all the text available in each file.

**Comment by jlooper** [comment]
Hello, we have completed translation of Traditional Chinese; we will need to differentiate for Simplified Chinese. Can you let me know if you'd like to continue here?

**Comment by morenyang** [comment]
> Hello, we have completed translation of Traditional Chinese; we will need to differentiate for Simplified Chinese. Can you let me know if you'd like to continue here?

@jlooper  Oh sorry, I'm soo busy these months😢.
There are many differences between the wordings in Simplified Chinese and Traditional Chinese. 
I can close this MR first and reopen when I have time to continue this job.

**Pull request closed without merging**
