### PR TITLE
Updated README.hi.md

### PR DESCRIPTION
**Pull request by Anant-mishra1729**
* Corrected wrong translations.
* Modified Lessons table.
* Inserted PDF and Other Curricula sections.

### CODE REVIEW

**Comment by Anant-mishra1729** [comment]
> @Anant-mishra1729 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="Anant Mishra"]

**Comment by Anant-mishra1729** [comment]
@microsoft-github-policy-service agree

**Review by AngieG44 — APPROVED** [review]

**Comment by saragibby** [comment]
@Anant-mishra1729 thank you for submitting these updates! There appears to be a conflict with this translation file that needs to be resolved. Once you resolve these conflicts we can review your changes.

**Review by saragibby — APPROVED** [review]
Thank you @Anant-mishra1729 for taking the time to update these translations!

**Pull request merged**
