### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by captainWaheed**
I just updated the README file with a PDF preview by embedding it.

### CODE REVIEW

**Review by vaibhav4516 — COMMENTED** [review]
I thinks that's a nice update.
Thanks, Happy Coding

**Comment by sinedied** [comment]
@captainWaheed PDF embeds does not seem to work on GitHub, did you test it?

**Comment by captainWaheed** [comment]
> @captainWaheed PDF embeds does not seem to work on GitHub, did you test it?

Yes I tested it with few methods but this one is working well.

**Comment by BigBro17on25tolife** [comment]
I’m looking for assistance in learning how to code using Solidity application, can you help

**Comment by sinedied** [comment]
@captainWaheed I if look at the GitHub preview on your branch, this is what I see:
image
The preview isn't visible, GitHub seems to block it for PDFs as a security measure.

**Comment by captainWaheed** [comment]
> @captainWaheed I if look at the GitHub preview on your branch, this is what I see: image The preview isn't visible, GitHub seems to block it for PDFs as a security measure.

Oh, I see! The last time I committed changes this was working fine, anyway I guess you were right. Thanks for the confirmation.

**Review by imlakshay08 — APPROVED** [review]

**Pull request closed without merging**
