### PR TITLE
assignment.gr.md

### PR DESCRIPTION
**Pull request by dimitrismokkas**
assignment lesson 1 greek translation

### CODE REVIEW

**Comment by jlooper** [comment]
Wow! Would you like to create one big draft PR and progressively add the translations to that ( see the other PRs here for an example) thank you 🙏!

**Comment by dimitrismokkas** [comment]
Yes, i think i could help with that. Althought i'm busy this period and my PR propably won't be  very consistent, at least for the moment.
I would also like to make a question(i'm brand new in Git and GitHub). Do i have to do/change something for the unsuccessful checks(Azure Static Web Apps CI/CD / Build and Deploy Job (pull_request))? Is it my fault? Thanks a lot :)

**Comment by dimitrismokkas** [comment]
> Wow! Would you like to create one big draft PR and progressively add the translations to that ( see the other PRs here for an example) thank you 🙏!

Yes, i think i could help with that. Althought i'm busy this period and my PR propably won't be  very consistent, at least for the moment.
I would also like to make a question(i'm brand new in Git and GitHub). Do i have to do/change something for the unsuccessful checks(Azure Static Web Apps CI/CD / Build and Deploy Job (pull_request))? Is it my fault? Thanks a lot :)

**Comment by jlooper** [comment]
hi, in that case I will approve this PR and the other one, and you can restart a new draft PR and add to it progressively for the lessons that need to be translated to Greek. Thank you!

Don't worry about the CI/CD job failing; that's the quiz-app build process that fails to build when external PRs occur. 

cheers! 
Jen

**Review by jlooper — APPROVED** [review]

**Pull request merged**
