### PR TITLE
Ch 1 - Italian translation, assignments and quizzes

### PR DESCRIPTION
**Pull request by robertopauletto**

### CODE REVIEW

**Comment by jlooper** [comment]
hi, thank you! We have changed the way we are adding quiz localizations, if you are interested in migrating: there's a separate /quiz-app to edit if you can. thanks!

**Comment by robertopauletto** [comment]
Ok, I will do that, I suppose you can discard my last PR then

**Comment by jlooper** [comment]
Maybe you can edit this one?

**Comment by robertopauletto** [comment]
HI Jen,
Here's another commit with the translated json for the quizzes

**Pull request merged**
