### PR TITLE
Updated web documentation

### PR DESCRIPTION
**Pull request by ajhawkings**
Added Microsoft Edge developer docs and web.dev

### CODE REVIEW

**Review by jlooper — CHANGES_REQUESTED** [review]
Hi, this is a nice addition but we need all translations updated as well to accept a PR

**Comment by ajhawkings** [comment]
Sure thing - I’ll get onto this…

**Comment by ajhawkings** [comment]
@jlooper I've now added other languages in my fork, but I think GitHub had an outage, and is not showing the commit here, despite it telling me that I could add commits by pushing to my fork (which I did)! Is it possible to open another PR to get it to recognise the changes or is there another way to force the PR to look for my changes? Thanks for the help.

**Comment by jlooper** [comment]
Hi! That’s weird. Yes, open a new PR, I’ll close this one

**Pull request closed without merging**
