### PR TITLE
Added persian (fa) translation

### PR DESCRIPTION
**Pull request by Chamepp**
## What is new in this pull request?
Made **Persian (fa)** translation available.

## What steps have been taken?
- [x] Created readme file in ``README.[language].md`` format following the ISO 639-1 standard
- [x] Translated the ``README.fa.md`` file
- [x] Added translation to the **quiz-app** by creating ``fa.json`` in the [translations](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/quiz-app/src/assets/translations) folder.
- [x] No need for adding your language code to the dropdown in the quiz app's App.vue file while it lists locales automatically, for the new update #442.
- [x] Imported **_fa_** and added it to **messages** in translations [index.js](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/quiz-app/src/assets/translations/index.js) file
- [x] Updated quiz-app link in new translated ``README.fa.md`` file for the Persian version
```diff
-      https://ashy-river-0debb7803.1.azurestaticapps.net
+     https://ashy-river-0debb7803.1.azurestaticapps.net?loc=fa
```

### CODE REVIEW

**Comment by Chamepp** [comment]
@leestott can I have feedback on my pull request, its been two months since my request

**Comment by Chamepp** [comment]
@microsoft-github-policy-service agree

**Comment by Chamepp** [comment]
> @Chamepp please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by Chamepp** [comment]
@microsoft-github-policy-service agree

**Comment by Chamepp** [comment]
thanks @leestott, This is my first pull request and I'm a bit confused. Does it take time for the bot to check my agreement with CLA?
and also I mistakenly committed my changes for my new pull request, should I revert it or let it stay?

**Comment by Chamepp** [comment]
Everythings complete, ready to get merged

**Review by saragibby — APPROVED** [review]
Thank you for making this updating and adding these translations!

**Comment by Chamepp** [comment]
Happy to be part of this 😄

**Pull request merged**
