### PR TITLE
Fixes in documentation / Assignees: @12rashic

### PR DESCRIPTION
**Pull request by kant**
* paragraphs 14, 30, 34, 38, 44, 116, 162, 199

### CODE REVIEW

**Comment by 12rashic** [comment]
Please assign this issue to me

**Comment by kant** [comment]
@12rashic Assigned to your persona!

**Comment by 12rashic** [comment]
HI @kant could you please provide more information about what fixes in documentation,

**Comment by kant** [comment]
@12rashic Typos fixed in these paragraphs 14, 30, 34, 38, 44, 116, 162, 199

**Comment by saragibby** [comment]
@abrilurena when you have a chance it would be great if you could give this translation PR a review. Thank you!

**Review by abrilurena — APPROVED** [review]
¡Muchas gracias, @kant !

**Comment by saragibby** [comment]
@kant it looks like this PR has some conflicts. Once you get the conflicts resolved we can merge this work in. Thank you!

**Comment by saragibby** [comment]
@kant when you have time, there is a conflict in a file to resolve. Once that is resolved we can merge these changes in. Thanks!

**Review by abrilurena — APPROVED** [review]
¡Mil gracias por tu ayuda y tiempo, @kant! ya aprobe estos cambios ✨

**Comment by abrilurena** [comment]
@kant por cierto, me aparece que es necesario que se solucione esto en tu rama antes de añadirlos cambios al repositorio principal: 

image

quedo al pendiente de cualquier duda, muchas gracias! :)

**Comment by kant** [comment]
Seems that I do not have the attributes needed to resolve this issues. I am closing this pull request to verify again if there are any prevalent issue.

**Pull request closed without merging**
