### PR TITLE
Fix: corrected reference link from previous lesson

### PR DESCRIPTION
**Pull request by ThesllaDev**

### CODE REVIEW

**Review by jlooper — CHANGES_REQUESTED** [review]
ah, nice catch.  Would you mind peeking at the translations and ensuring they are corrected as well?

**Comment by ThesllaDev** [comment]
> 
> 
> ah, nice catch. Would you mind peeking at the translations and ensuring they are corrected as well?

Thanks! I would love to continue contributing to this repository and the community, how do I proceed?

**Comment by jlooper** [comment]
hi, if you look in the lesson's translations folder you can find translated README.md files to edit, so we can keep consistent. thanks!

**Comment by jlooper** [comment]
hi, it shouldn't make a difference, as you are editing the folder name: `../1-about-browsers` which is probably wrong in the translated README's if it's wrong in the main README.

**Review by jlooper — APPROVED** [review]
looking good! thanks

**Pull request merged**
