### PR TITLE
Add indonesian translations (2-js-basics)

### PR DESCRIPTION
**Pull request by hexatester**
- [x] 2-js-basics
- [x] 1-data-types
- [x] 2-functions-methods
- [x] 3-making-decisions
- [x] 4-arrays-loops

### CODE REVIEW

**Comment by paladique** [comment]
@hexatester thank you so much!

**Comment by kartik4patel34343** [comment]
Thanks to all this

**Comment by amode101** [comment]
hi

**Comment by hexatester** [comment]
Looks good for me. Ready to merge. @jlooper

**Review by jlooper — APPROVED** [review]
Thanks! Please note we have a new quiz app with translations if you’d like to migrate the quizzes there 🙏

**Comment by kartik4patel34343** [comment]
yes. this looks good for to all. 
Ready to merge

**Pull request merged**
