### PR TITLE
added Gujarati translation

### PR DESCRIPTION
**Pull request by SKVKPandey**

### CODE REVIEW

**Comment by han9912** [comment]
Hi Shashank, Please reply with 

> @microsoft-github-policy-service agree

**Comment by SKVKPandey** [comment]
@microsoft-github-policy-service agree

**Comment by SKVKPandey** [comment]
> @microsoft-github-policy-service agree

**Comment by SKVKPandey** [comment]
> Hi Shashank, Please reply with
> 
> > @microsoft-github-policy-service agree

**Comment by SKVKPandey** [comment]
@microsoft-github-policy-service agree

**Comment by SKVKPandey** [comment]
@microsoft-github-policy-service agree

**Pull request closed without merging**
