### PR TITLE
added switch statement

### PR DESCRIPTION
**Pull request by Charishma-Bailapudi**

### CODE REVIEW

**Comment by Charishma-Bailapudi** [comment]
@microsoft-github-policy-service agree [company="Gayatri Vidya Parishad College Of Engineering"]

**Comment by Charishma-Bailapudi** [comment]
@microsoft-github-policy-service agree company="Gayatri Vidya Parishad College Of Engineering "

**Comment by Charishma-Bailapudi** [comment]
@microsoft-github-policy-service agree

**Review by saragibby — APPROVED** [review]
This is a great addition to the decisions lesson, thank you for adding!

**Pull request merged**
