### PR TITLE
updates readme.md with information of switch case statment in js-basi…

### PR DESCRIPTION
**Pull request by kituuu**
added switch case statement in js-basics/making-decisions

### CODE REVIEW

**Comment by kituuu** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by PATTNAIKABHINANDAN** [comment]
heyy!!!can I contribute??

**Review by PATTNAIKABHINANDAN — COMMENTED** [review]
I want to contribute. I have some changes to be suggested.

**Comment by kituuu** [comment]
> I want to contribute. I have some changes to be suggested. 

Why are u telling me?? 🥲🥲 I am not a maintainer, I'm a contributor.

**Comment by kituuu** [comment]
@alfredodeza Hey, can you review and suggest changes in my pull request.

**Pull request closed without merging**
