### PR TITLE
un-translate code

### PR DESCRIPTION
**Pull request by han9912**
The PR un-translates a language confusion caused by a translation to Italian before.

### CODE REVIEW

**Comment by han9912** [comment]
> @han9912 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by han9912** [comment]
@microsoft-github-policy-service agree

**Comment by han9912** [comment]
Hi @saragibby , Azure Static Web Apps CI/CD / Build and Deploy Job failed with `deployment_token was not provided.`
Is there anything I can do about it?

**Review by saragibby — APPROVED** [review]
Thank you for spotting and making these corrections! The deployment pipeline is for the quiz app, since these changes don't apply to that it is not an issue that the deployment failed.

**Pull request merged**
