### PR TITLE
fix: Broken Badge (Open in Visual Studio Code) & Add: more ml translations

### PR DESCRIPTION
**Pull request by Justinjdaniel**

### CODE REVIEW

**Comment by Justinjdaniel** [comment]
If the badge is unnecessary, please let me know and I will remove the broken badge.
Thanks

**Comment by sinedied** [comment]
Thanks for the fix!

Would it be possible to use the recommended replacement: `https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc`
instead as suggested [in this issue](https://github.com/microsoft/vscode/issues/128813)?

It should be a quick search & replace 😉

**Comment by Justinjdaniel** [comment]
> Thanks for the fix!
> 
> Would it be possible to use the recommended replacement: `https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc` instead as suggested [in this issue](https://github.com/microsoft/vscode/issues/128813)?
> 
> It should be a quick search & replace 😉

Sure

**Comment by Justinjdaniel** [comment]
Done.

**Comment by sinedied** [comment]
Thanks!

**Pull request merged**
