### PR TITLE
[zh-cn] add typing-game/assignment.zh-cn.md 

### PR DESCRIPTION
**Pull request by ChungZH**

### CODE REVIEW

**Review by MelnikovAG — COMMENTED** [review]
Bomber One

**Comment by Cololandi** [comment]
Landi26

**Comment by Cololandi** [comment]
[**ka**]()

**Comment by Cololandi** [comment]
> Bomber One

**Review by jlooper — APPROVED** [review]

**Comment by Cololandi** [comment]
> > Bomber One
> 
>

**Pull request merged**
