### PR TITLE
Added PT-BR Translations for 6-space-game

### PR DESCRIPTION
**Pull request by FranciscoHeronildo**
Realized translated the `6-space-game` README to PT-BR (Brazilian Portuguese)

### CODE REVIEW

**Comment by FranciscoHeronildo** [comment]
@microsoft-github-policy-service agree

**Comment by FranciscoHeronildo** [comment]
@microsoft-github-policy-service agree [company="FranciscoHeronildo"]

**Comment by FranciscoHeronildo** [comment]
@microsoft-github-policy-service agree

**Review by Sticknmove — APPROVED** [review]
Thanks

**Comment by saragibby** [comment]
@PabloNunes when you have a chance, could you review this translations PR? Thank you!

**Review by PabloNunes — APPROVED** [review]
Review:

- README translation to PT-BR
- Correct folder and naming structure

Status: Merge Approved

**Pull request merged**
