### PR TITLE
Translate README, for-teachers Malayalam & Open in Visual Studio Code Badge

### PR DESCRIPTION
**Pull request by Justinjdaniel**
Translate README Malayalam

Signed-off-by: Justin J Daniel <62233773+Justinjdaniel@users.noreply.github.com>

### CODE REVIEW

**Comment by jlooper** [comment]
I like the badge! Would you mind moving it below the status badges, and if possible update this file's translations too?

**Comment by jlooper** [comment]
Also, please check all the paths, including images, to make sure they point back to the original or to a translation if it's available. Thanks!

**Comment by Justinjdaniel** [comment]
- Checked and corrected all paths
- Added Badge in original README and translated README
- Is it okay if I add Badge to all other translated READMEs?

**Comment by Justinjdaniel** [comment]
changed path of PDF in translate main README with full path. (wrt. Issue #507 )

**Review by jlooper — APPROVED** [review]

**Pull request merged**
