### PR TITLE
Chore improvements

### PR DESCRIPTION
**Pull request by HemantSachdeva**
expecting a merger before 31st October ;)

### CODE REVIEW

**Comment by HemantSachdeva** [comment]
> 

@microsoft-github-policy-service agree

**Comment by HemantSachdeva** [comment]
> @HemantSachdeva please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by HemantSachdeva** [comment]
@leestott any reviews?

**Review by saragibby — APPROVED** [review]
Thank you for adding this additions to the README and TRANSLATION instructions!

**Comment by HemantSachdeva** [comment]
> Thank you for adding this additions to the README and TRANSLATION instructions!

My pleasure mam.
Now there are conflicts in the merger. Do you wnat me to resolve them?

**Comment by saragibby** [comment]
@HemantSachdeva that would be great if you can resolve the conflicts. As soon as resolved we'll get this merged.

**Comment by HemantSachdeva** [comment]
> @HemantSachdeva that would be great if you can resolve the conflicts. As soon as resolved we'll get this merged.

I can resolve the conflicts but can't push them to this PR because the fork was deleted by mistake so I would have to make a new PR I guess.

Only person with write access to this repo can update this PR with resolved conflicts.

**Comment by HemantSachdeva** [comment]
@saragibby [Commit 1](https://github.com/HemantSachdeva/Web-Dev-For-Beginners/commit/5c4c85ab3a05bc83522e27f37fede1a22f2d96f1) and [Commit 2](https://github.com/HemantSachdeva/Web-Dev-For-Beginners/commit/df7e711642ee45f3e5aa29727f6756c7d8ac40d7) could be merged without any conflicts so may I make another PR?

**Comment by saragibby** [comment]
@HemantSachdeva another PR works as well. Tag me in it and I will try to get to it as soon as it is opened.

**Comment by HemantSachdeva** [comment]
Done mam :)

**Pull request closed without merging**
