### PR TITLE
Added a new project

### PR DESCRIPTION
**Pull request by virtualwiz1**
# A simple project for beginners to better learn JavaScript
### Features
- Simple project structure
- Easy to follow methods
- Comments added
- Minimalistic
- Live preview available on mentioned link
### Live Preview on:
[Live Preview for project](https://virtualwiz1.github.io/js-projects/quizapp/)

### CODE REVIEW

**Comment by virtualwiz1** [comment]
I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
@microsoft-github-policy-service agree [company="{your company}"]

**Comment by virtualwiz1** [comment]
I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

@microsoft-github-policy-service agree
@microsoft-github-policy-service agree company="your company"

**Comment by virtualwiz1** [comment]
@microsoft-github-policy-service agree
@microsoft-github-policy-service agree company="your company"

**Comment by virtualwiz1** [comment]
@microsoft-github-policy-service agree

**Comment by Manish12-verma** [comment]
i want to add my new project in this repository for the hacktoberfest

**Comment by saragibby** [comment]
Thank you @virtualwiz1 for your suggestion. This is a great project, but more advanced than this material aims to complete. For now, the best place to share this project would be in our **Show and Tell** - https://github.com/microsoft/Web-Dev-For-Beginners/discussions/categories/show-and-tell.

Closing this PR so you can share sample project within Discussions. When we build out the ability to onboard additional projects to our repo for extra practice and exercises we will announce to the community. Thank you!

**Pull request closed without merging**
