### PR TITLE
Adding pdf working link

### PR DESCRIPTION
**Pull request by keshavgbpecdelhi**
wrt #507

### CODE REVIEW

**Review by jlooper — CHANGES_REQUESTED** [review]
Is there a possibility to add this edit to all the homepage translations?

**Comment by keshavgbpecdelhi** [comment]
Docsify is not able to get an html page from # , while other links are fine. I think it's just the functioning of it which is not letting that link work internally.

**Comment by jlooper** [comment]
> Docsify is not able to get an html page from # , while other links are fine. I think it's just the functioning of it which is not letting that link work internally.

Maybe I wasn't clear - can you add this link to all the versions of this page that exist in the /translations folder, so as to make sure the translated versions are aligned to this change? thanks!

**Comment by keshavgbpecdelhi** [comment]
Oo now I get it, Thanks.

**Comment by jlooper** [comment]
Ready for merge?

**Pull request merged**
