### PR TITLE
Added README Translation in Thai (th)

### PR DESCRIPTION
**Pull request by teeradon43**
- Added `README.th.md` for the main `README.md` file

PS: I left any untranslated documents in English topic. When I (or another Thai translator) translate the lesson to Thai, I'll edit them as a proper name

### CODE REVIEW

**Comment by teeradon43** [comment]
@microsoft-github-policy-service agree

**Comment by teeradon43** [comment]
@saragibby Hello. I have a question. Can I start translating other documents, or should I wait for this PR to be approved first?

**Comment by MandisiMgidi** [comment]
@microsoft-github-policy-service agree

**Review by saragibby — APPROVED** [review]
Thank you @teeradon43 for adding this translation! Please feel free to translate any additional files, submitting a PR for each file. Appreciate your time and effort to ensure this curriculum is available for more people.

**Pull request merged**
