### PR TITLE
translate 1-getting-started-lesson into japanese

### PR DESCRIPTION
**Pull request by silverskyvicto**
Hi.

I translate 1-getting-started-lesson into japanese.

How about this?

### CODE REVIEW

**Comment by jlooper** [comment]
Love it!! Arigato!

**Comment by silverskyvicto** [comment]
@jlooper 
Thank you for checking.

I'm getting the following error on CI / CD, does this mean I need to configure something?

```
azure_static_web_apps_api_token was not provided.
The azure_static_web_apps_api_token is required for deploying content. If you'd like to continue the workflow run without deployment, add the workflow configuration skip_deploy_on_missing_secrets set to true
```

**Comment by jlooper** [comment]
> @jlooper
> Thank you for checking.
> 
> I'm getting the following error on CI / CD, does this mean I need to configure something?
> 
> ```
> azure_static_web_apps_api_token was not provided.
> The azure_static_web_apps_api_token is required for deploying content. If you'd like to continue the workflow run without deployment, add the workflow configuration skip_deploy_on_missing_secrets set to true
> ```

hi, this error has to do with the quiz app, stored in /quiz-app and running as an Azure static web app. You don't need to worry about that until you translate the quizzes, which I'm working on right now to support localization. You can run the quiz app locally if you need to - go to that folder and follow the instructions in the README to run on localhost.

**Comment by jlooper** [comment]
@silverskyvicto is this ready to merge?

**Comment by silverskyvicto** [comment]
@jlooper 

> @silverskyvicto is this ready to merge?

Yes.

**Pull request merged**
