### PR TITLE
added git and github basics for web dev beginner👶

### PR DESCRIPTION
**Pull request by Yashkapure06**
I have given detailed explanation of each and every basic git commands. Any beginner can understand the concept of GIT after following this *Git Cheat Sheet*.

### CODE REVIEW

**Comment by Yashkapure06** [comment]
> @Yashkapure06 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="{default}"]

**Comment by Yashkapure06** [comment]
> @Yashkapure06 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by RaheemAmer — APPROVED** [review]
LGTM

**Comment by Yashkapure06** [comment]
> LGTM

What does it means? 🙂

**Comment by RaheemAmer** [comment]
> > LGTM
> 
> What does it means? 🙂

"Looks good to me"

**Comment by Yashkapure06** [comment]
> > > LGTM
> > 
> > 
> > What does it means? 🙂
> 
> "Looks good to me"

Oh okay Thanks!! What do you think will they merge this?🙃

**Comment by Yashkapure06** [comment]
@leestott Hello Sir, Can you please tell me why this is occuring
image

**Comment by han9912** [comment]
Hello, I faced with the same error with yours, and I don't know if there's anything I can do about it.

**Comment by Yashkapure06** [comment]
> Hello, I faced with the same error with yours, and I don't know if there's anything I can do about it.

@han9912 Even I dont have any idea about it..

**Pull request closed without merging**
