### PR TITLE
Translate the Dutch files

### PR DESCRIPTION
**Pull request by noah-vdv**
### Dutch files

- [x] quiz
- [x] assignments
- [ ] README's
  - [ ] 2 - 2
  - [ ] 2 - 3
  - [ ] 2 - 4
  - [x] 3
  - [ ] 3 - 1
  - [ ] 3 - 2
  - [ ] 3 - 3
  - [x] 4
  - [ ] 4 - typing-game
  - [x] 5
  - [ ] 5 - solution
  - [ ] 5 - start
  - [ ] 5 - 1
  - [ ] 5 - 2
  - [ ] 5 - 3
  - [x] 6
  - [ ] 6 - 1
  - [ ] 6 - 2
  - [ ] 6 - 3
  - [ ] 6 - 4
  - [ ] 6 - 5
  - [ ] 6 - 6
  - [x] 7
  - [ ] 7 - api
  - [ ] 7 - solution
  - [ ] 7 - 1
  - [ ] 7 - 2
  - [ ] 7 - 3
  - [ ] 7 - 4

### CODE REVIEW

**Comment by noah-vdv** [comment]
Also, line 267 from the 1-getting-started-lessons/2-github-basics/README.md file has a typo (at least I think).

**Comment by jlooper** [comment]
> Also, line 267 from this ["You will want to copy the contents of to our machine"](https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/1-getting-started-lessons/2-github-basics/README.md#how-to-contribute-to-open-source) file has a typo (at least I think).

thank you, fixed!

**Comment by noah-vdv** [comment]
If an article is translated (e.g wikipedia) should I change it to that version?

**Comment by jlooper** [comment]
> If an article is translated (e.g wikipedia) should I change it to that version?

good question, yes I think so

**Review by EmmStewie2709 — COMMENTED** [review]
**D I R E T S O •̀.̫•́**

**Review by EmmStewie2709 — APPROVED** [review]

**Review by EmmStewie2709 — COMMENTED** [review]
D I R E T S O •̀.̫•́

**Review by EmmStewie2709 — COMMENTED** [review]
D I R E T S O •̀.̫•́

**Review by EmmStewie2709 — COMMENTED** [review]
D I R E T S O •̀.̫•́

**Review by EmmStewie2709 — COMMENTED** [review]
D I R E T S O.•̀.̫•́

**Comment by noah-vdv** [comment]
This is probably as far as I'm going to get at the moment since I don't have that much spare time. So I think it's good to merge.

**Comment by sa970** [comment]
Why u close it

Sent from my iPhone

‫في 21‏/03‏/2021 الساعة 8:42 م، كتب/كتبت ‏Noah van der Veer ***@***.***>:‬

﻿

This is probably as far as I'm going to get at the moment since I don't have that much spare time. So I think it's good to merge.

**Comment by sa970** [comment]
I respect u why u did this


Sent from my iPhone

‫في 21‏/03‏/2021 الساعة 8:42 م، كتب/كتبت ‏Noah van der Veer ***@***.***>:‬

﻿

This is probably as far as I'm going to get at the moment since I don't have that much spare time. So I think it's good to merge.

**Comment by jlooper** [comment]
> I respect u why u did this
> […](#)
> Sent from my iPhone ‫في 21‏/03‏/2021 الساعة 8:42 م، كتب/كتبت ‏Noah van der Veer ***@***.***>:‬ ﻿ This is probably as far as I'm going to get at the moment since I don't have that much spare time. So I think it's good to merge. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FWeb-Dev-For-Beginners%2Fpull%2F225%23issuecomment-803630062&data=04%7C01%7C%7C8b38b4305b33478e536708d8ec90b51a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637519453537415297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=a8M01FsFBxo4Aq2ysRI%2FIYYlnFZqutk0xbL8VAdmn3A%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATKRHPPQ4OMJV7D4BQMLXMTTEYVYRANCNFSM4YWTTO7A&data=04%7C01%7C%7C8b38b4305b33478e536708d8ec90b51a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637519453537425257%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ISiqyfrV55xGqJXKhbR4P802gO2iGVCp1M%2BJerAy5dc%3D&reserved=0>.

I don't know what you're talking about, but please keep the conversation on this thread to the topic of the Dutch translations.

**Review by jlooper — APPROVED** [review]
thank you for fixing some of the non-Dutch typos as well!

**Comment by mwkrix777** [comment]
import matplotlib.pyplot as plt fig, ax = plt.subplots() ax.broken_barh([(110, 30), (150, 10)], (10, 9), facecolors='tab:blue') ax.broken_barh([(10, 50), (100, 20), (130, 10)], (20, 9), facecolors=('tab:orange', 'tab:green', 'tab:red')) ax.set_ylim(5, 35) ax.set_xlim(0, 200) ax.set_xlabel('seconds since start') ax.set_yticks([15, 25]) ax.set_yticklabels(['Bill', 'Jim']) ax.grid(True) ax.annotate('race interrupted', (61, 25), xytext=(0.8, 0.9), textcoords='axes fraction', arrowprops=dict(facecolor='black', shrink=0.05), fontsize=16, horizontalalignment='right', verticalalignment='top') plt.show() ssl.pl

**Comment by milliondollarbabe11** [comment]
ok thanks im fine, really Appreciate it

**Pull request merged**
