### PR TITLE
Translation zh-cn

### PR DESCRIPTION
**Pull request by AqingCyan**
👋 Hi
I am very enthusiastic about this project and hope to translate some simplified Chinese content every week. It is really fun.

### CODE REVIEW

**Comment by jlooper** [comment]
Thank you! I know some has been done but much appreciate completing the missing parts!

**Comment by AqingCyan** [comment]
But I still don't know what is the standard process of contribution translation。😰
I'm a little confused by the above error。

**Comment by AqingCyan** [comment]
I wish I could keep translating the documents

**Comment by jlooper** [comment]
> I wish I could keep translating the documents

Hi, here is the guide: https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/TRANSLATIONS.md - feel free to continue and thanks! I just wanted to mention that some simplified Chinese and I believe all traditional Chinese translations are complete, but if you find missing translations please add yours! 🙏

**Comment by AqingCyan** [comment]
> > I wish I could keep translating the documents
> 
> Hi, here is the guide: https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/TRANSLATIONS.md - feel free to continue and thanks! I just wanted to mention that some simplified Chinese and I believe all traditional Chinese translations are complete, but if you find missing translations please add yours! 🙏

OK！I found that some chapters were lacking in simplified Chinese, and I will translate at least two per week.

**Review by Chongruiyuan893 — COMMENTED** [review]
What do I have to do

**Review by jlooper — APPROVED** [review]
looks good, thanks!

**Pull request merged**
