### PR TITLE
Adding Git Log Command

### PR DESCRIPTION
**Pull request by Prashant-Bhapkar**

### CODE REVIEW

**Comment by Prashant-Bhapkar** [comment]
Hello Team,
@mattetti @chanezon @arschles @saragibby 

I have made some changes by adding the git log command.

Looking forward to hearing from you.

**Comment by saragibby** [comment]
This is a good idea to add into the GitHub lesson, as `git log` is a handy command to know. To keep the first task simple to introduce `git` commands it would be better to move this to the follow on task for "Task: Merge some code". Utilizing `git log` within that task would be helpful to demostate how `git log` can be used.

**Comment by saragibby** [comment]
@Prashant-Bhapkar pinging you to see if you can make the updates by moving this section as noted. Will leave this pull request open a bit longer to give you time, otherwise we will close due to inactivity.

**Comment by saragibby** [comment]
Closing this PR in favor of issue #1108 that covers the addition of `git log` to the [2-github-basics](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics) lesson.

**Pull request closed without merging**
