### PR TITLE
🚀 feat(Js Polyfills): Added some JS polyfills

### PR DESCRIPTION
**Pull request by Abhishek765**
### Polyfills Covered :
- Map
- Filter
- Reduce
- Promise
- PromiseAll

### CODE REVIEW

**Comment by Abhishek765** [comment]
@microsoft-github-policy-service agree

**Comment by Abhishek765** [comment]
@saragibby   can you have a look and let me know if it looks good to you :)

**Comment by Abhishek765Flyfin** [comment]
Hi, please try to look into this PR and kindly add `hacktoberfest-accepted` label

**Comment by Abhishek765** [comment]
Hi, please try to look into this PR and kindly add `hacktoberfest-accepted` label

**Comment by Abhishek765** [comment]
hi @saragibby  can you merge this PR ?

**Comment by Abhishek765** [comment]
hi @saragibby can you merge this PR ?

**Comment by saragibby** [comment]
Thank you for your suggestion to add these polyfill examples! We are currently not expanding this to any new lessons and projects. But this would definitely be a great learning for future enhancements. Stay tuned for when we open contributions for additional lessons, and example web apps to build. For now, sharing your creations within [Discussions](https://github.com/microsoft/Web-Dev-For-Beginners/discussions) would be amazing!

**Pull request closed without merging**
