### PR TITLE
Translation PT

### PR DESCRIPTION
**Pull request by pachicodes**
Translation of : Getting started readme and Intro to programming language readme to Portuguese

### CODE REVIEW

**Comment by jlooper** [comment]
hi @pachicodes ! @glaucia86 some more Portuguese! Maybe we can join with the other PR

**Comment by pachicodes** [comment]
@jlooper is that ok if I week translating this? or do already have a contributor?

**Comment by jlooper** [comment]
Hi @pachicodes ! There’s another PT translation started here so can you collab with them? ♥️🙏

**Comment by pachicodes** [comment]
Sure @jlooper ! Is @glaucia86 the other translator?

**Review by alli03106 — APPROVED** [review]

**Comment by OmoruyiTessy** [comment]
I am sorry

tessy

**Comment by manman1500** [comment]
[]@jlooper

**Comment by manman1500** [comment]
https://www.facebook.com/puwanarth.chanthanaphumma.1

**Comment by manman1500** [comment]
https://www.facebook.com/puwanarth.chanthanaphumma.1@sinedied

**Comment by manman1500** [comment]
https://www.facebook.com/puwanarth.chanthanaphumma.1

**Review by manman1500 — COMMENTED** [review]
https://www.facebook.com/puwanarth.chanthanaphumma.1

**Review by manman1500 — APPROVED** [review]
https://www.facebook.com/puwanarth.chanthanaphumma.1@pachicodes

**Review by manman1500 — APPROVED** [review]
https://www.facebook.com/puwanarth.chanthanaphumma.1

**Review by manman1500 — COMMENTED** [review]
0991615378

**Review by manman1500 — COMMENTED** [review]
0991615378

**Review by manman1500 — APPROVED** [review]
https://www.facebook.com/puwanarth.chanthanaphumma.1

**Comment by manman1500** [comment]
0991615378

**Comment by jlooper** [comment]
hi @pachicodes! should I merge this?

**Comment by pachicodes** [comment]
Hi @jlooper yes please!

**Review by jlooper — APPROVED** [review]

**Comment by jlooper** [comment]
thank you!

**Pull request merged**
