### PR TITLE
Create file assignment.es.md

### PR DESCRIPTION
**Pull request by FranciscoImanolSuarez**
Create file assignment.es.md

This file was not in the central repository.

### CODE REVIEW

**Comment by FranciscoImanolSuarez** [comment]
Hi @jlooper 

Can you help me here?

What would be the process to follow?

Thanks!

**Comment by jlooper** [comment]
hi, you can create this file in the proper /translations folder and send the PR, thanks

**Review by jlooper — COMMENTED** [review]
looks good!

**Comment by Vdan29** [comment]
What is it?

**Comment by FranciscoImanolSuarez** [comment]
Hi @Vdan29.

It is a PR, in which I add the translation of a file to Spanish.

You can learn more about "PR" in the next section [GitHub Basic](https://github.com/microsoft/Web-Dev-For-Beginners/tree/main/1-getting-started-lessons/2-github-basics)

**Pull request merged**
