### PR TITLE
✨ feat(Complete JavaScript): All JS concepts

### PR DESCRIPTION
**Pull request by tush-tr**
- Added Complete Module for Almost complete JavaScript.
## Topics added:
- Values and Variables- Premitive data types- Numbers
- How JavaScript works?
- Premitive data types- Boolean, Null, Undefined, String
- Control and logic flow- if/else, switch, ternary operator, logical operators etc.
- Arrays, array methods
- Objects in JavaScript
- Loops in JavaScript
- Functions in JavaScript
- Scope,Function expressions, Higher Order functions, callbacks, hoisting
- Array callback methods- filter, forEach, reduce, map, some, every etc.
- Default Parameters, Spreads,Rest Parameters, Destructuring
- Object Methods and the "This" Keyword
- Document Object Model
- Communicating with Events
- Asynchronous JavaScript, Callbacks and Promises
- Making http requests: Fetch, Axios
- Async and Await 
- Prototypes, Classes, & the new operator
- JavaScript with Node.js

### CODE REVIEW

**Comment by tush-tr** [comment]
@microsoft-github-policy-service agree [company="default"]

**Comment by tush-tr** [comment]
@microsoft-github-policy-service agree

**Comment by tush-tr** [comment]
```
@microsoft-github-policy-service agree
```

**Comment by tush-tr** [comment]
@microsoft-github-policy-service agree

**Comment by saragibby** [comment]
Thank you for your suggestion to add these JS examples and lesson! We are currently not expanding this to any new lessons and projects. But stay tuned for when we open contributions for additional lessons, and example web apps to build. For now, sharing your creations within [Discussions](https://github.com/microsoft/Web-Dev-For-Beginners/discussions) would be amazing!

**Pull request closed without merging**
