### PR TITLE
Rock Paper Scissor Game Added

### PR DESCRIPTION
**Pull request by khushhal7**
I develop a Rock Paper Scissor Game Using HTML, CSS, and JavaScript.

### CODE REVIEW

**Comment by khushhal69** [comment]
> @microsoft-github-policy-service agree [company="{your company}"]

@microsoft-github-policy-service agree [company="{JECRC Foundation}"]

**Comment by khushhal69** [comment]
@microsoft-github-policy-service agree [company="{default}"]

**Comment by khushhal69** [comment]
@microsoft-github-policy-service agree

**Comment by khushhal69** [comment]
> @microsoft-github-policy-service agree company="I'm a Student"

**Comment by khushhal69** [comment]
@microsoft-github-policy-service agree company="Jaipur Engineering College And Research Centre"

**Comment by saragibby** [comment]
Thank you for your suggestion to add a rock/paper/scissors game! We are currently not expanding this to any new lessons and projects. But stay tuned for when we open contributions for additional lessons, and example web apps to build. For now, sharing your creations within [Discussions](https://github.com/microsoft/Web-Dev-For-Beginners/discussions) would be amazing!

**Pull request closed without merging**
