### PR TITLE
hacktoberfest-2022

### PR DESCRIPTION
**Pull request by anurag464**
Please add my folder to in your repository  label hacktoberfest.

It's a GUI drum kit game.

### CODE REVIEW

**Comment by anurag464** [comment]
default

**Comment by anurag464** [comment]
@microsoft-github-policy-service agree [company="{deafult}"]

**Comment by anurag464** [comment]
@microsoft-github-policy-service agree [company="{default}"]

**Comment by anurag464** [comment]
@microsoft-github-policy-service agree company=default

**Comment by saragibby** [comment]
Thank you @anurag464 for your suggestion. This is a fun project. For now, as this is a great project for additional practice, the best place to share your creation would be in [**Show and Tell**](https://github.com/microsoft/Web-Dev-For-Beginners/discussions/categories/show-and-tell).

Closing this PR so you can share this sample project within Discussions. When we build out the ability to onboard additional projects to our repo for extra practice and exercises, we will announce to the community. Thank you!

**Pull request closed without merging**
