### PR TITLE
Updated Swahili

### PR DESCRIPTION
**Pull request by Tridence**

### CODE REVIEW

**Review by jlooper — CHANGES_REQUESTED** [review]
Hi, thank you for your contribution. Could you edit the headings to standard markup, such that `# # # wahariri` should be `## Wahariri` - with standard capitalization and markdown format in place. Thank you!

**Comment by Tridence** [comment]
Thank you. Nitafanya ipasavyo!

**Review by Tridence — COMMENTED** [review]
changed wahariri to Wahariri

**Comment by jlooper** [comment]
hi, could you go through the whole file please and make sure all the markdown matches the README.md format - for example match the use of ##, ### and #### if there are any. Also the header 'Windows' is duplicated. thank you!

**Review by Tridence — COMMENTED** [review]
Sorted the markdown file, deleted the repeated Windows header as well.

**Comment by Tridence** [comment]
COMPLETE!

**Pull request closed without merging**
