### PR TITLE
Add helpwanted part

### PR DESCRIPTION
**Pull request by devisasari**
I added help wanted part!

Happy "Hacktoberfest"!

### CODE REVIEW

**Comment by devisasari** [comment]
> 

@microsoft-github-policy-service agree

**Comment by jonasermert** [comment]
@microsoft-github-policy-service agree

**Comment by devisasari** [comment]
> 

Hey bot! Don't close this PR. Thank you!

**Comment by jonasermert** [comment]
Hey bot! Don't close this PR. Thank you!

**Review by saragibby — APPROVED** [review]
Thank you for adding this missing translation and adding the help wanted section!

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Pull request merged**
