### PR TITLE
Portuguese translation of Terrarium (base README and 1-intro-to-html)

### PR DESCRIPTION
**Pull request by iluminnatti**
I made the portugue (pt-BR) translation for the Terrarium's folder. I translated the base README.md (of the terrarium's folder) and linked it to this portuguese translation. Besides that, I translated the README file of the 1-intro-to-html folder and the assignment file (same folder). Furthuermore, I linked the root README.pt-BR.md to this translation. So, I guess this first part of the folder is completely translated. I'm here to solve any problem and question.

### CODE REVIEW

**Comment by iluminnatti** [comment]
#341 

- [x] 3-terrarium base README
- [x] intro-to-html README
- [x]  intro-to-html assignment

**Review by jlooper — APPROVED** [review]
I wonder if we should audit to make sure we have both pt-br and pt covered. But approving 🙏

**Comment by jlooper** [comment]
Is there a way you could resolve the conflicts here, please?

**Comment by iluminnatti** [comment]
Sure, you're right. My translation is to brazillian portuguese (pt-BR). I'm gonna solve this problem right now.

**Review by jlooper — APPROVED** [review]

**Pull request merged**
