### PR TITLE
[fr] 5-3-readme french translation

### PR DESCRIPTION
**Pull request by ManuSquall**
Add README.fr.md file for 5-3-background-tasks-and-performance

### CODE REVIEW

**Review by jlooper — APPROVED** [review]
merci!

**Review by Pornprasert — COMMENTED** [review]
Hi

**Comment by ManuSquall** [comment]
> Hi

Hello there! Thanks for the review 🥳

**Comment by ManuSquall** [comment]
> merci!

Un plaisir :-)

**Pull request merged**
