### PR TITLE
Add designing and css styles

### PR DESCRIPTION
**Pull request by dazzle-sah**
I have added background color, font styling and improved their alignments.

### CODE REVIEW

**Comment by dazzle-sah** [comment]
I have read the license agreement.

**Comment by dazzle-sah** [comment]
Both the GitHub Ids (@drishtisah , @dazzle-sah ) belong to me. There is no employer agreement.

**Comment by aditi824** [comment]
I want to contribute to this issue.

**Comment by dazzle-sah** [comment]
yes you can

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by saragibby** [comment]
Thank you for your styling suggestions @dazzle-sah! We purposefully left styling out of the typing game to keep focus on the lesson content. For now, the best place to show how you extended this lesson is within [**Show and Tell**](https://github.com/microsoft/Web-Dev-For-Beginners/discussions/categories/show-and-tell).

Closing this PR so you can share this sample project within Discussions. If/When we add the ability to onboard lesson enhancements we will announce to the community. Thank you!

**Pull request closed without merging**
