### PR TITLE
made readme.md readable .

### PR DESCRIPTION
**Pull request by SATYAM1548**
I found as this project is for web-dev-beginners, But there is not enough content in ReadMe.md on how to get started with docsify also there was no script in package.json to run docsify

My changes 

1.ReadMe.md
image

image

2.package.json

image

### CODE REVIEW

**Comment by SATYAM1548** [comment]
@microsoft-github-policy-service agree

**Comment by SATYAM1548** [comment]
@MelnikovAG 
hello !
can u have a look to this pr under hacktober fest.
thanks.

**Review by Sticknmove — COMMENTED** [review]
Thanks

**Review by Sticknmove — APPROVED** [review]
Thanks

**Review by Sticknmove — APPROVED** [review]
Thank you.

**Comment by SATYAM1548** [comment]
@Sticknmove 
Is this pull request going to be merged ?

**Comment by SATYAM1548** [comment]
@Sticknmove 
hello , these changes are only approved what I need to do so that it gets merged.
thanks

**Review by Sticknmove — APPROVED** [review]

**Comment by SATYAM1548** [comment]
> @SATYAM1548 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Pull request closed without merging**
