### PR TITLE
Update CONTRIBUTING.md for PR clarity

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
Adding the fact that you should try to specify why you made a certain change when creating a pull request. This change was made at the end of the second paragraph of CONTRIBUTING.md to add this instruction.

### CODE REVIEW

**Comment by alfredodeza** [comment]
I'm not sure I'm following the reasoning for this change. When a pull request is created, it already has the ability to show what the changes are and where they are. What would the benefit be of asking someone to repeat the same information in the description?

**Comment by SmashedFrenzy16** [comment]
Some people do not specify where the change occured

**Comment by softchris** [comment]
@SmashedFrenzy16 I think there's value in adding the "Why" but I agree with Alfredo on the where. Could you please modify it to only speak on the why and we can approve it?

**Comment by SmashedFrenzy16** [comment]
I will change it as soon as possible

**Comment by SmashedFrenzy16** [comment]
@softchris I have changed the file and my original comment to only include the "Why" part.

**Review by alfredodeza — APPROVED** [review]

**Pull request merged**
