### PR TITLE
L3xi42 patch 2

### PR DESCRIPTION
**Pull request by l3xi42**
I corrected some grammar mistakes

### CODE REVIEW

**Review by naaji-navas — APPROVED** [review]

**Review by saragibby — APPROVED** [review]
Thank you for spotting these items and getting them fixed!

**Comment by saragibby** [comment]
@l3xi42 these changes look good to merge. All we need is your agreement to the contributor license agreement and the conflicts resolved. Once those are complete, we can merge. Thank you!

**Comment by saragibby** [comment]
@l3xi42 along with needing your contributor agreement, there is now some conflicts to be resolved on this PR. Once both are taking care of we can get this merged. Thanks!

**Comment by saragibby** [comment]
Closing this pull request as it is missing contributor agreement and has unresolved conflicts.

**Pull request closed without merging**
