### PR TITLE
Italian Translation - Ch. 5

### PR DESCRIPTION
**Pull request by robertopauletto**
Hi, 

just a thought regarding the extension installation instructions: maybe it's worth specify that you have to enable "Developer mode" first in order to see "Load unpacked", by default this mode is disabled. You can see this in the screenshot anyway but after all we are addressing beginners...

1-about browser
- After "Take a minute to look through the codebase:" may a code block directive is missing when you specify the directory structure of the app?

- "build your extension using npm build" should be "build your extension using npm **run** build"?

3-background task and performance

- This link is broken:
You'll learn more about the Canvas API in the [Space Game lessons](../../space-game/drawing-to-canvas/README.md).
I think should be
You'll learn more about the Canvas API in the [Space Game lessons](../../6-space-game/2-drawing-to-canvas/README.md).

Thanks!

### CODE REVIEW

**Comment by jlooper** [comment]
Cc @softchris - I love how the translations help clarify the English instructions 😍

**Review by jlooper — COMMENTED** [review]
hi @robertopauletto question - I don't think we want to translate the code in the /dist folder of the browser extension, not sure what you are proposing here?

**Comment by robertopauletto** [comment]
I'm sorry,  I realize that I have not been clear.

First of all, I forgot to translate the readme.md in the /solution/dist folder, which I have done now.

I was referring to the comments, labels and strings in the html and js files for the /solution/dist folder. 

For the start folder it's ok because the student can follow along more clearly ma for the final solution code I'm not sure if I have to do this.



--
  Roberto Pauletto
  roberto.pauletto@gmail.com

**Comment by han9912** [comment]
@jlooper @robertopauletto Hi, thanks for the translation! But I think it's necessary to use English to avoid confusion, when there's no specification that it's a translation. So I open [pull request]( #915 ) to revert the translation to English. 
Awaiting your review, thanks.

**Comment by robertopauletto** [comment]
HI,

fine by me

Bye

--
  Roberto Pauletto
  ***@***.***

**Comment by jlooper** [comment]
I'm no longer a maintainer but thank you for your continued work here 💓

**Pull request merged**
