### PR TITLE
BMI Calculator beginner

### PR DESCRIPTION
**Pull request by SHaf373**
This File Contain basic Code of Java Script to make BMI Calculator

### CODE REVIEW

**Comment by AbhayKatoch** [comment]
I want to contribute.

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by SHaf373** [comment]
> @microsoft-github-policy-service agree [company="{Muhammad Shaf Hameed(myself)"]

**Comment by SHaf373** [comment]
> @SHaf373 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by SHaf373** [comment]
@microsoft-github-policy-service agree

**Comment by SHaf373** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by saragibby** [comment]
Thank you for your suggestion to add a BMI calculator app! We are currently not expanding this to any new lessons and projects. But stay tuned for when we open contributions for additional lessons, and example web apps to build. For now, sharing your creations within [Discussions](https://github.com/microsoft/Web-Dev-For-Beginners/discussions) would be amazing!

**Pull request closed without merging**
