### PR TITLE
fix incorrect answer in quiz

### PR DESCRIPTION
**Pull request by mkleczewski**
Incorrect answer marked as true in first question of prelecture quiz for lesson 3

That answer should not be true unless there exists such a tool (I couldn't find it anywhere)

Edit: incorrect answer also present in other translations

### CODE REVIEW

**Review by Clam-u — COMMENTED** [review]
Fuels

**Comment by sinedied** [comment]
@mkleczewski Thanks for the catch!

Would it be possible for you to also fix all translations in this PR, so they're in sync? Thanks a lot

**Comment by mkleczewski** [comment]
@sinedied done

**Comment by sinedied** [comment]
Awesome, thanks!

**Review by Clam-u — COMMENTED** [review]
nice

**Review by Sticknmove — COMMENTED** [review]
Thanks

**Review by Sticknmove — COMMENTED** [review]
Thanks

**Review by Sticknmove — COMMENTED** [review]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Review by Sticknmove — COMMENTED** [review]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Pull request merged**
